### ISSUE TITLE
Cannot convert feathernetb model to caffe model.

### ISSUE THREAD

**Issue by songinmok63** [SoftwareGift/Pytorch2Caffe#2]
Hello, thank you for your contribution.
I have tried to convert feathernetb model to caffemodel. but there is a problem following

Traceback (most recent call last):
  File "pytorch2caffe.py", line 56, in <module>
    pytorch_to_caffe.trans_net(net, input, name)
  File "/home/oezfr/Pytorch2Caffe/PytorchToCaffe/pytorch_to_caffe.py", line 614, in trans_net
    out = net.forward(input_var)
  File "/home/oezfr/Pytorch2Caffe/PytorchToCaffe/models/FeatherNet.py", line 135, in forward
    x = self.features(x)
  File "/home/oezfr/anaconda3/envs/oezfr/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/oezfr/anaconda3/envs/oezfr/lib/python3.6/site-packages/torch/nn/modules/container.py", line 92, in forward
    input = module(input)
  File "/home/oezfr/anaconda3/envs/oezfr/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/oezfr/Pytorch2Caffe/PytorchToCaffe/models/FeatherNet.py", line 80, in forward
    return self.downsample(x) + self.conv(x)
  File "/home/oezfr/anaconda3/envs/oezfr/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/oezfr/anaconda3/envs/oezfr/lib/python3.6/site-packages/torch/nn/modules/container.py", line 92, in forward
    input = module(input)
  File "/home/oezfr/anaconda3/envs/oezfr/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/oezfr/anaconda3/envs/oezfr/lib/python3.6/site-packages/torch/nn/modules/pooling.py", line 554, in forward
    self.padding, self.ceil_mode, self.count_include_pad, self.divisor_override)
  File "/home/oezfr/Pytorch2Caffe/PytorchToCaffe/pytorch_to_caffe.py", line 536, in __call__
    out=self.obj(self.raw,*args,**kwargs)
TypeError: _avg_pool2d() takes from 3 to 7 positional arguments but 8 were given

How can I fix them?
Thank you.

**Comment by songinmok63** [comment]
Oh, I run, 
python pytorch2caffe.py FeatherNetB ~/bin/_104_best.20200720.pth.tar

**Comment by riskeverything** [comment]
did you fix it？I use the pytorch to caffe,but some error is in view sent.
